export const ALL_USER_REQUREST = 'ALL_USER_REQUREST'
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS'

export const ALL_TRANSACTION_REQUREST = 'ALL_TRANSACTION_REQUREST'
export const ALL_TRANSACTION_SUCCESS = 'ALL_TRANSACTION_SUCCESS'

export const ADD_NAME = 'ADD_NAME'
export const REMOVE_NAME = 'REMOVE_NAME'
